import { HealthCondition, DietaryRestriction, HealthRule } from '../types';

export const MASTER_HEALTH_CONDITIONS: HealthCondition[] = [
  {
    code: 'none',
    nameEn: 'No specific conditions',
    nameMl: 'പ്രത്യേക അസുഖങ്ങൾ ഒന്നുമില്ല',
    descriptionEn: 'General healthy nutrition guidance',
    descriptionMl: 'പൊതുവായ ആരോഗ്യകരമായ പോഷകാഹാര നിർദ്ദേശങ്ങൾ',
    isActive: true,
  },
  {
    code: 'diabetes',
    nameEn: 'Diabetes / Blood Sugar Concerns',
    nameMl: 'പ്രമേഹം / രക്തത്തിലെ പഞ്ചസാര',
    descriptionEn: 'Focus on low added sugars and balanced carbohydrates with high fibre',
    descriptionMl: 'കുറഞ്ഞ പഞ്ചസാരയും നാരുകൾ അടങ്ങിയ കാർബോഹൈഡ്രേറ്റും',
    isActive: true,
  },
  {
    code: 'prediabetes',
    nameEn: 'Prediabetes',
    nameMl: 'പ്രീഡയബറ്റിസ് (പ്രമേഹ സാധ്യത)',
    descriptionEn: 'Limit refined sugars and high glycemic loads',
    descriptionMl: 'പഞ്ചസാരയുടെ അളവ് പരിമിതപ്പെടുത്തുക',
    isActive: true,
  },
  {
    code: 'hypertension',
    nameEn: 'High Blood Pressure (Hypertension)',
    nameMl: 'ഉയർന്ന രക്തസമ്മർദ്ദം (ഹൈപ്പർടെൻഷൻ)',
    descriptionEn: 'Strict monitoring of sodium and salt content',
    descriptionMl: 'ഉപ്പിന്റെയും സോഡിയത്തിന്റെയും അളവ് കർശനമായി ശ്രദ്ധിക്കുക',
    isActive: true,
  },
  {
    code: 'high_cholesterol',
    nameEn: 'High Cholesterol / Lipid Concerns',
    nameMl: 'ഉയർന്ന കൊളസ്ട്രോൾ',
    descriptionEn: 'Limit saturated fat and eliminate trans fat',
    descriptionMl: 'പൂരിത കൊഴുപ്പ് കുറയ്ക്കുകയും ട്രാൻസ് ഫാറ്റ് ഒഴിവാക്കുകയും ചെയ്യുക',
    isActive: true,
  },
  {
    code: 'weight_management',
    nameEn: 'Weight Management / Obesity',
    nameMl: 'ശരീരഭാരം നിയന്ത്രിക്കൽ',
    descriptionEn: 'Calorie awareness, low added sugars, and adequate protein and fibre',
    descriptionMl: 'കുറഞ്ഞ കലോറിയും പഞ്ചസാരയും, ആവശ്യത്തിന് പ്രോട്ടീനും നാരുകളും',
    isActive: true,
  },
  {
    code: 'heart_health',
    nameEn: 'Heart Health Concerns',
    nameMl: 'ഹൃദയാരോഗ്യം',
    descriptionEn: 'Low sodium, low saturated fat, and zero trans fat',
    descriptionMl: 'കുറഞ്ഞ സോഡിയവും പൂരിത കൊഴുപ്പും',
    isActive: true,
  },
  {
    code: 'kidney_disease',
    nameEn: 'Kidney Disease',
    nameMl: 'വൃക്കരോഗം',
    descriptionEn: 'Requires specialized clinical evaluation (MVP provides non-clinical notice)',
    descriptionMl: 'ഡോക്ടറുടെ പ്രത്യേക നിർദ്ദേശം ആവശ്യമാണ്',
    isActive: true,
  },
  {
    code: 'other',
    nameEn: 'Other Health Concerns',
    nameMl: 'മറ്റ് ആരോഗ്യ പ്രശ്നങ്ങൾ',
    descriptionEn: 'Custom condition without automatic medical heuristic scoring',
    descriptionMl: 'മറ്റ് ആരോഗ്യ സാഹചര്യങ്ങൾ',
    isActive: true,
  },
];

export const MASTER_DIETARY_PREFERENCES: DietaryRestriction[] = [
  {
    code: 'none',
    type: 'preference',
    nameEn: 'No Preference',
    nameMl: 'പ്രത്യേക മുൻഗണനകളില്ല',
    isActive: true,
  },
  {
    code: 'vegetarian',
    type: 'preference',
    nameEn: 'Vegetarian (No meat/fish)',
    nameMl: 'സസ്യാഹാരം (വെജിറ്റേറിയൻ)',
    isActive: true,
  },
  {
    code: 'vegan',
    type: 'preference',
    nameEn: 'Vegan (100% plant-based)',
    nameMl: 'വീഗൻ (സമ്പൂർണ്ണ സസ്യഭക്ഷണം)',
    isActive: true,
  },
  {
    code: 'eggetarian',
    type: 'preference',
    nameEn: 'Eggetarian (Vegetarian with eggs)',
    nameMl: 'എഗ്ഗറ്റേറിയൻ (മുട്ട കഴിക്കുന്നവർ)',
    isActive: true,
  },
];

export const MASTER_ALLERGENS: DietaryRestriction[] = [
  {
    code: 'milk',
    type: 'allergen',
    nameEn: 'Milk / Dairy',
    nameMl: 'പാൽ / പാലുൽപ്പന്നങ്ങൾ',
    isActive: true,
  },
  {
    code: 'lactose',
    type: 'allergen',
    nameEn: 'Lactose',
    nameMl: 'ലാക്ടോസ്',
    isActive: true,
  },
  {
    code: 'peanut',
    type: 'allergen',
    nameEn: 'Peanut',
    nameMl: 'നിലക്കടല',
    isActive: true,
  },
  {
    code: 'tree_nuts',
    type: 'allergen',
    nameEn: 'Tree Nuts (Almonds, Cashews, Walnuts, etc.)',
    nameMl: 'കശുവണ്ടി, ബദാം തുടങ്ങിയ നട്ടുകൾ',
    isActive: true,
  },
  {
    code: 'soy',
    type: 'allergen',
    nameEn: 'Soy / Soya',
    nameMl: 'സോയ',
    isActive: true,
  },
  {
    code: 'wheat_gluten',
    type: 'allergen',
    nameEn: 'Wheat / Gluten',
    nameMl: 'ഗോതമ്പ് / ഗ്ലൂട്ടൻ',
    isActive: true,
  },
  {
    code: 'egg',
    type: 'allergen',
    nameEn: 'Egg',
    nameMl: 'മുട്ട',
    isActive: true,
  },
  {
    code: 'fish',
    type: 'allergen',
    nameEn: 'Fish',
    nameMl: 'മത്സ്യം',
    isActive: true,
  },
  {
    code: 'shellfish',
    type: 'allergen',
    nameEn: 'Shellfish / Prawns / Crab',
    nameMl: 'ചെമ്മീൻ / ഞണ്ട്',
    isActive: true,
  },
  {
    code: 'sesame',
    type: 'allergen',
    nameEn: 'Sesame',
    nameMl: 'എള്ള്',
    isActive: true,
  },
];

export const DEFAULT_HEURISTIC_RULES: HealthRule[] = [
  // Diabetes & Prediabetes Rules (Per 100g)
  {
    id: 'rule-diabetes-added-sugar-high',
    conditionCode: 'diabetes',
    nutrient: 'addedSugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 10,
    severity: 'high',
    deduction: 30,
    messageEn: 'High added sugar content (≥10g per 100g), which may cause rapid blood glucose spikes.',
    messageMl: 'കൂടുതൽ അളവിൽ ചേർത്ത പഞ്ചസാര അടങ്ങിയിരിക്കുന്നു (100 ഗ്രാമിൽ 10 ഗ്രാമിൽ കൂടുതൽ), ഇത് രക്തത്തിലെ പഞ്ചസാര വർദ്ധിപ്പിച്ചേക്കാം.',
    adviceEn: 'Look for packaged foods with under 5g added sugars per 100g.',
    adviceMl: '100 ഗ്രാമിൽ 5 ഗ്രാമിൽ താഴെ പഞ്ചസാരയുള്ള ഉൽപ്പന്നങ്ങൾ തിരഞ്ഞെടുക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-diabetes-added-sugar-mod',
    conditionCode: 'diabetes',
    nutrient: 'addedSugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 5,
    severity: 'moderate',
    deduction: 15,
    messageEn: 'Moderate added sugar (≥5g per 100g). Consume in mindful moderation.',
    messageMl: 'മിതമായ അളവിൽ പഞ്ചസാര അടങ്ങിയിരിക്കുന്നു. അളവ് നിയന്ത്രിച്ച് ഉപയോഗിക്കുക.',
    adviceEn: 'Prefer whole-grain snacks with higher dietary fibre.',
    adviceMl: 'കൂടുതൽ നാരുകൾ അടങ്ങിയ ലഘുഭക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-diabetes-sugars-high',
    conditionCode: 'diabetes',
    nutrient: 'sugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 15,
    severity: 'high',
    deduction: 25,
    messageEn: 'Total sugars exceed 15g per 100g.',
    messageMl: 'ആകെ പഞ്ചസാര 100 ഗ്രാമിൽ 15 ഗ്രാമിൽ കൂടുതലാണ്.',
    adviceEn: 'Choose unsweetened alternatives.',
    adviceMl: 'മധുരം ചേർക്കാത്ത ഉൽപ്പന്നങ്ങൾ തിരഞ്ഞെടുക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-prediabetes-sugar-high',
    conditionCode: 'prediabetes',
    nutrient: 'addedSugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 8,
    severity: 'high',
    deduction: 25,
    messageEn: 'High added sugar may accelerate risk of insulin resistance.',
    messageMl: 'ഉയർന്ന അളവിലുള്ള പഞ്ചസാര പ്രമേഹ സാധ്യത വർദ്ധിപ്പിച്ചേക്കാം.',
    adviceEn: 'Look for low sugar (<5g/100g) snacks.',
    adviceMl: 'കുറഞ്ഞ പഞ്ചസാര അടങ്ങിയ ലഘുഭക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക.',
    isActive: true,
  },

  // Hypertension / High Blood Pressure Rules (Per 100g)
  {
    id: 'rule-hypertension-sodium-critical',
    conditionCode: 'hypertension',
    nutrient: 'sodiumMg',
    basis: 'per_100g',
    operator: '>=',
    threshold: 800,
    severity: 'critical',
    deduction: 35,
    messageEn: 'Very high sodium content (≥800mg per 100g), which significantly impacts blood pressure.',
    messageMl: 'വളരെ ഉയർന്ന അളവിൽ സോഡിയം/ഉപ്പ് അടങ്ങിയിരിക്കുന്നു (100 ഗ്രാമിൽ 800 മില്ലിഗ്രാമിൽ കൂടുതൽ).',
    adviceEn: 'Look for low sodium products (<140mg per 100g or <0.3g salt).',
    adviceMl: 'കുറഞ്ഞ സോഡിയം അടങ്ങിയ ഉൽപ്പന്നങ്ങൾ തിരഞ്ഞെടുക്കുക (100 ഗ്രാമിൽ 140 മില്ലിഗ്രാമിൽ താഴെ).',
    isActive: true,
  },
  {
    id: 'rule-hypertension-sodium-high',
    conditionCode: 'hypertension',
    nutrient: 'sodiumMg',
    basis: 'per_100g',
    operator: '>=',
    threshold: 500,
    severity: 'high',
    deduction: 20,
    messageEn: 'High sodium content (≥500mg per 100g).',
    messageMl: 'കൂടുതൽ സോഡിയം അടങ്ങിയിരിക്കുന്നു.',
    adviceEn: 'Consider items with reduced sodium options.',
    adviceMl: 'കുറഞ്ഞ ഉപ്പുള്ള ഉൽപ്പന്നങ്ങൾ തിരഞ്ഞെടുക്കാൻ ശ്രദ്ധിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-hypertension-sodium-mod',
    conditionCode: 'hypertension',
    nutrient: 'sodiumMg',
    basis: 'per_100g',
    operator: '>=',
    threshold: 350,
    severity: 'moderate',
    deduction: 10,
    messageEn: 'Moderate sodium content. Limit portion size.',
    messageMl: 'മിതമായ സോഡിയം അടങ്ങിയിരിക്കുന്നു.',
    isActive: true,
  },

  // High Cholesterol & Heart Health Rules
  {
    id: 'rule-cholesterol-satfat-high',
    conditionCode: 'high_cholesterol',
    nutrient: 'saturatedFatG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 5,
    severity: 'high',
    deduction: 25,
    messageEn: 'High saturated fat (≥5g per 100g), which may elevate LDL cholesterol.',
    messageMl: 'പൂരിത കൊഴുപ്പ് (സാച്ചുറേറ്റഡ് ഫാറ്റ്) കൂടുതലാണ്, ഇത് കൊളസ്ട്രോൾ വർദ്ധിപ്പിച്ചേക്കാം.',
    adviceEn: 'Choose products with <1.5g saturated fat per 100g.',
    adviceMl: '100 ഗ്രാമിൽ 1.5 ഗ്രാമിൽ താഴെ സാച്ചുറേറ്റഡ് ഫാറ്റ് ഉള്ളവ തിരഞ്ഞെടുക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-cholesterol-transfat',
    conditionCode: 'high_cholesterol',
    nutrient: 'transFatG',
    basis: 'per_100g',
    operator: '>',
    threshold: 0.1,
    severity: 'critical',
    deduction: 30,
    messageEn: 'Contains trans fats, which are strictly advised against for cardiovascular health.',
    messageMl: 'ട്രാൻസ് ഫാറ്റ് അടങ്ങിയിരിക്കുന്നു, ഇത് ഹൃദയാരോഗ്യത്തിന് ദോഷകരമാണ്.',
    adviceEn: 'Choose 0g trans fat foods with healthy unsaturated oils.',
    adviceMl: 'പൂർണ്ണമായും ട്രാൻസ് ഫാറ്റ് ഇല്ലാത്ത ഭക്ഷണങ്ങൾ തിരഞ്ഞെടുക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-heart-sodium-satfat',
    conditionCode: 'heart_health',
    nutrient: 'saturatedFatG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 4,
    severity: 'high',
    deduction: 20,
    messageEn: 'Elevated saturated fat content for heart health.',
    messageMl: 'ഹൃദയാരോഗ്യത്തിന് അനുയോജ്യമല്ലാത്ത അളവിൽ സാച്ചുറേറ്റഡ് ഫാറ്റ് അടങ്ങിയിരിക്കുന്നു.',
    isActive: true,
  },

  // Weight Management
  {
    id: 'rule-weight-energy-high',
    conditionCode: 'weight_management',
    nutrient: 'energyKcal',
    basis: 'per_100g',
    operator: '>=',
    threshold: 450,
    severity: 'moderate',
    deduction: 15,
    messageEn: 'High energy density (≥450 kcal per 100g).',
    messageMl: 'കൂടിയ കലോറി സാന്ദ്രത (100 ഗ്രാമിൽ 450 കിലോ കലോറിയിൽ കൂടുതൽ).',
    adviceEn: 'Consume smaller portions or pair with high-fibre snacks.',
    adviceMl: 'അളവ് കുറച്ച് കഴിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-weight-sugar-high',
    conditionCode: 'weight_management',
    nutrient: 'sugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 12,
    severity: 'moderate',
    deduction: 15,
    messageEn: 'High sugar content contributes empty calories.',
    messageMl: 'കൂടുതൽ പഞ്ചസാര ശരീരഭാരം വർദ്ധിക്കാൻ കാരണമായേക്കാം.',
    isActive: true,
  },
];

export const MANDATORY_MEDICAL_DISCLAIMER_EN =
  'This app provides general nutrition information and personalized food guidance based on the information you provide. It is not medical advice and does not replace advice from a qualified healthcare professional.';

export const MANDATORY_MEDICAL_DISCLAIMER_ML =
  'ഈ ആപ്പ് നൽകുന്നത് പൊതുവായ പോഷകാഹാര വിവരങ്ങളും നിങ്ങളുടെ തിരഞ്ഞെടുപ്പുകൾക്ക് അനുസൃതമായ നിർദ്ദേശങ്ങളും മാത്രമാണ്. ഇത് വൈദ്യോപദേശമല്ല, ഡോക്ടറുടെ നിർദ്ദേശങ്ങൾക്ക് പകരമാവില്ല.';
