import { Product } from '@health-scanner/shared';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    barcode: '8901030000010',
    name: 'Parle-G Glucose Biscuits',
    brand: 'Parle',
    category: 'Biscuits',
    servingSize: '30g',
    servingSizeUnit: 'g',
    imageUrl: 'https://images.openfoodfacts.org/images/products/890/103/000/0010/front_en.3.400.jpg',
    nutritionPer100g: {
      energyKcal: 454,
      carbohydratesG: 78.2,
      sugarsG: 25.5,
      addedSugarsG: 22.0,
      proteinG: 6.5,
      fatG: 13.0,
      saturatedFatG: 6.0,
      transFatG: 0.0,
      fibreG: 1.8,
      sodiumMg: 280,
      saltG: 0.7,
    },
    ingredientsText: 'Refined Wheat Flour (Maida) (67%), Sugar (22%), Refined Palm Oil, Invert Sugar Syrup, Milk Solids (1%), Raising Agents, Salt.',
    ingredientsList: [
      'refined wheat flour (maida)',
      'sugar',
      'refined palm oil',
      'invert sugar syrup',
      'milk solids',
      'raising agents',
      'salt',
    ],
    detectedAllergens: ['wheat_gluten', 'milk'],
    source: 'internal',
    sourceConfidence: 1.0,
  },
  {
    id: 'prod-002',
    barcode: '8901063012345',
    name: 'Marie Gold Biscuits',
    brand: 'Britannia',
    category: 'Biscuits',
    servingSize: '25g',
    servingSizeUnit: 'g',
    nutritionPer100g: {
      energyKcal: 435,
      carbohydratesG: 77.0,
      sugarsG: 21.0,
      addedSugarsG: 19.5,
      proteinG: 8.0,
      fatG: 10.5,
      saturatedFatG: 4.8,
      transFatG: 0.0,
      fibreG: 2.5,
      sodiumMg: 310,
      saltG: 0.78,
    },
    ingredientsList: [
      'refined wheat flour (maida)',
      'sugar',
      'refined palm oil',
      'invert syrup',
      'milk solids',
      'iodised salt',
      'wheat fibre',
    ],
    detectedAllergens: ['wheat_gluten', 'milk'],
    source: 'internal',
    sourceConfidence: 1.0,
  },
  {
    id: 'prod-003',
    barcode: '8901058852278',
    name: 'Maggi 2-Minute Masala Noodles',
    brand: 'Nestlé',
    category: 'Instant Noodles',
    servingSize: '70g',
    servingSizeUnit: 'g',
    nutritionPer100g: {
      energyKcal: 427,
      carbohydratesG: 63.5,
      sugarsG: 2.2,
      addedSugarsG: 1.5,
      proteinG: 8.0,
      fatG: 15.7,
      saturatedFatG: 6.8,
      transFatG: 0.12,
      fibreG: 3.6,
      sodiumMg: 1050,
      saltG: 2.6,
    },
    ingredientsList: [
      'refined wheat flour (maida)',
      'palm oil',
      'iodised salt',
      'wheat gluten',
      'hydrolysed groundnut protein',
      'mixed spices (onion powder, coriander, turmeric, chilli powder, garlic powder, cumin, aniseed, ginger)',
      'sugar',
      'flavour enhancer (635)',
    ],
    detectedAllergens: ['wheat_gluten', 'peanut'],
    source: 'internal',
    sourceConfidence: 1.0,
  },
  {
    id: 'prod-004',
    barcode: '8901491101807',
    name: "Lay's India's Magic Masala Potato Chips",
    brand: "Lay's",
    category: 'Snacks & Chips',
    servingSize: '30g',
    servingSizeUnit: 'g',
    nutritionPer100g: {
      energyKcal: 544,
      carbohydratesG: 52.8,
      sugarsG: 3.2,
      addedSugarsG: 2.0,
      proteinG: 7.0,
      fatG: 33.7,
      saturatedFatG: 15.2,
      transFatG: 0.1,
      fibreG: 3.9,
      sodiumMg: 820,
      saltG: 2.05,
    },
    ingredientsList: [
      'potato',
      'edible vegetable oil (palmolein)',
      'seasoning (spices and condiments, salt, maltodextrin, sugar, milk solids, mango powder, acidity regulators)',
    ],
    detectedAllergens: ['milk'],
    source: 'internal',
    sourceConfidence: 1.0,
  },
  {
    id: 'prod-005',
    barcode: '8901207040125',
    name: 'Quaker Rolled Oats 100% Whole Grain',
    brand: 'Quaker',
    category: 'Breakfast Cereals',
    servingSize: '40g',
    servingSizeUnit: 'g',
    nutritionPer100g: {
      energyKcal: 389,
      carbohydratesG: 66.0,
      sugarsG: 0.8,
      addedSugarsG: 0.0,
      proteinG: 12.5,
      fatG: 8.5,
      saturatedFatG: 1.6,
      transFatG: 0.0,
      fibreG: 10.2,
      sodiumMg: 5,
      saltG: 0.01,
    },
    ingredientsList: ['100% whole grain rolled oats'],
    detectedAllergens: ['wheat_gluten'],
    source: 'internal',
    sourceConfidence: 1.0,
  },
  {
    id: 'prod-006',
    barcode: '8901262010019',
    name: 'Amul Taaza Homogenised Toned Milk',
    brand: 'Amul',
    category: 'Dairy',
    servingSize: '200ml',
    servingSizeUnit: 'ml',
    nutritionPer100g: {
      energyKcal: 58,
      carbohydratesG: 4.7,
      sugarsG: 4.7,
      addedSugarsG: 0.0,
      proteinG: 3.1,
      fatG: 3.0,
      saturatedFatG: 1.9,
      transFatG: 0.0,
      fibreG: 0.0,
      sodiumMg: 50,
      saltG: 0.12,
    },
    ingredientsList: ['toned milk', 'vitamin a', 'vitamin d'],
    detectedAllergens: ['milk', 'lactose'],
    source: 'internal',
    sourceConfidence: 1.0,
  },
  {
    id: 'prod-007',
    barcode: '8906093850123',
    name: 'Epigamia Natural Greek Yogurt (No Added Sugar)',
    brand: 'Epigamia',
    category: 'Dairy',
    servingSize: '90g',
    servingSizeUnit: 'g',
    nutritionPer100g: {
      energyKcal: 85,
      carbohydratesG: 4.5,
      sugarsG: 4.5,
      addedSugarsG: 0.0,
      proteinG: 7.5,
      fatG: 4.0,
      saturatedFatG: 2.4,
      transFatG: 0.0,
      fibreG: 0.0,
      sodiumMg: 45,
      saltG: 0.11,
    },
    ingredientsList: ['pasteurized double toned milk', 'milk solids', 'active lactic cultures'],
    detectedAllergens: ['milk', 'lactose'],
    source: 'internal',
    sourceConfidence: 1.0,
  },
  {
    id: 'prod-008',
    barcode: '8901042971234',
    name: 'Real 100% Mixed Fruit Juice',
    brand: 'Real / Dabur',
    category: 'Beverages',
    servingSize: '200ml',
    servingSizeUnit: 'ml',
    nutritionPer100g: {
      energyKcal: 56,
      carbohydratesG: 14.0,
      sugarsG: 13.5,
      addedSugarsG: 7.0,
      proteinG: 0.4,
      fatG: 0.0,
      saturatedFatG: 0.0,
      transFatG: 0.0,
      fibreG: 0.5,
      sodiumMg: 15,
      saltG: 0.03,
    },
    ingredientsList: [
      'water',
      'mixed fruit concentrate (apple, banana, guava, mango, orange, pineapple)',
      'sugar',
      'acidity regulator (citric acid)',
      'antioxidant (ascorbic acid)',
    ],
    detectedAllergens: [],
    source: 'internal',
    sourceConfidence: 1.0,
  },
  {
    id: 'prod-009',
    barcode: '8901725131234',
    name: 'MTR Ready-to-Eat Paneer Butter Masala',
    brand: 'MTR',
    category: 'Ready to Eat',
    servingSize: '150g',
    servingSizeUnit: 'g',
    nutritionPer100g: {
      energyKcal: 168,
      carbohydratesG: 9.5,
      sugarsG: 4.0,
      addedSugarsG: 2.5,
      proteinG: 5.5,
      fatG: 12.0,
      saturatedFatG: 5.5,
      transFatG: 0.0,
      fibreG: 2.0,
      sodiumMg: 490,
      saltG: 1.2,
    },
    ingredientsList: [
      'water',
      'paneer (cottage cheese) (20%)',
      'tomato paste',
      'onion',
      'butter',
      'cashew nut',
      'edible vegetable oil',
      'cream',
      'sugar',
      'salt',
      'ginger garlic paste',
      'spices',
    ],
    detectedAllergens: ['milk', 'tree_nuts'],
    source: 'internal',
    sourceConfidence: 1.0,
  },
  {
    id: 'prod-010',
    barcode: '8901234567890',
    name: 'Acceptance Demo High-Sugar High-Sodium Snack',
    brand: 'Demo Brand',
    category: 'Snack Food',
    servingSize: '50g',
    servingSizeUnit: 'g',
    nutritionPer100g: {
      energyKcal: 480,
      carbohydratesG: 68.0,
      sugarsG: 28.0,
      addedSugarsG: 24.0,
      proteinG: 5.0,
      fatG: 21.0,
      saturatedFatG: 7.5,
      transFatG: 0.2,
      fibreG: 1.2,
      sodiumMg: 880,
      saltG: 2.2,
    },
    ingredientsList: [
      'wheat flour',
      'sugar',
      'vegetable oil',
      'milk solids',
      'salt',
      'flavouring agents',
    ],
    detectedAllergens: ['wheat_gluten', 'milk'],
    source: 'internal',
    sourceConfidence: 1.0,
  },
];
