import { HealthCondition, DietaryRestriction, HealthRule } from '../types';

export const RULE_SET_VERSION = '2026.1-audited';

export const MASTER_HEALTH_CONDITIONS: HealthCondition[] = [
  {
    code: 'none',
    nameEn: 'No specific conditions',
    nameMl: 'പ്രത്യേക അസുഖങ്ങൾ ഒന്നുമില്ല',
    descriptionEn: 'General healthy nutrition guidance',
    descriptionMl: 'പൊതുവായ ആരോഗ്യകരമായ പോഷകാഹാര നിർദ്ദേശങ്ങൾ',
    isActive: true,
  },
  {
    code: 'diabetes',
    nameEn: 'Diabetes / Blood Sugar Concerns',
    nameMl: 'പ്രമേഹം / രക്തത്തിലെ പഞ്ചസാര',
    descriptionEn: 'Focus on low added sugars and balanced carbohydrates with high fibre',
    descriptionMl: 'കുറഞ്ഞ പഞ്ചസാരയും നാരുകൾ അടങ്ങിയ കാർബോഹൈഡ്രേറ്റും',
    isActive: true,
  },
  {
    code: 'prediabetes',
    nameEn: 'Prediabetes',
    nameMl: 'പ്രീഡയബറ്റിസ് (പ്രമേഹ സാധ്യത)',
    descriptionEn: 'Limit refined sugars and high glycemic loads',
    descriptionMl: 'പഞ്ചസാരയുടെ അളവ് പരിമിതപ്പെടുത്തുക',
    isActive: true,
  },
  {
    code: 'hypertension',
    nameEn: 'High Blood Pressure (Hypertension)',
    nameMl: 'ഉയർന്ന രക്തസമ്മർദ്ദം (ഹൈപ്പർടെൻഷൻ)',
    descriptionEn: 'Strict monitoring of sodium and salt content',
    descriptionMl: 'ഉപ്പിന്റെയും സോഡിയത്തിന്റെയും അളവ് കർശനമായി ശ്രദ്ധിക്കുക',
    isActive: true,
  },
  {
    code: 'high_cholesterol',
    nameEn: 'High Cholesterol / Lipid Concerns',
    nameMl: 'ഉയർന്ന കൊളസ്ട്രോൾ',
    descriptionEn: 'Limit saturated fat and eliminate trans fat',
    descriptionMl: 'പൂരിത കൊഴുപ്പ് കുറയ്ക്കുകയും ട്രാൻസ് ഫാറ്റ് ഒഴിവാക്കുകയും ചെയ്യുക',
    isActive: true,
  },
  {
    code: 'weight_management',
    nameEn: 'Weight Management / Obesity',
    nameMl: 'ശരീരഭാരം നിയന്ത്രിക്കൽ',
    descriptionEn: 'Calorie awareness, low added sugars, and adequate protein and fibre',
    descriptionMl: 'കുറഞ്ഞ കലോറിയും പഞ്ചസാരയും, ആവശ്യത്തിന് പ്രോട്ടീനും നാരുകളും',
    isActive: true,
  },
  {
    code: 'heart_health',
    nameEn: 'Heart Health Concerns',
    nameMl: 'ഹൃദയാരോഗ്യം',
    descriptionEn: 'Low sodium, low saturated fat, and zero trans fat',
    descriptionMl: 'കുറഞ്ഞ സോഡിയവും പൂരിത കൊഴുപ്പും',
    isActive: true,
  },
  {
    code: 'kidney_disease',
    nameEn: 'Kidney Disease',
    nameMl: 'വൃക്കരോഗം',
    descriptionEn: 'Requires clinical medical management (advisory notice provided)',
    descriptionMl: 'ഡോക്ടറുടെ പ്രത്യേക നിർദ്ദേശം ആവശ്യമാണ്',
    isActive: true,
  },
  {
    code: 'other',
    nameEn: 'Other Health Concerns',
    nameMl: 'മറ്റ് ആരോഗ്യ പ്രശ്നങ്ങൾ',
    descriptionEn: 'Custom condition without automatic medical heuristic scoring',
    descriptionMl: 'മറ്റ് ആരോഗ്യ സാഹചര്യങ്ങൾ',
    isActive: true,
  },
];

export const MASTER_DIETARY_PREFERENCES: DietaryRestriction[] = [
  {
    code: 'none',
    type: 'preference',
    nameEn: 'No Preference',
    nameMl: 'പ്രത്യേക മുൻഗണനകളില്ല',
    isActive: true,
  },
  {
    code: 'vegetarian',
    type: 'preference',
    nameEn: 'Vegetarian (No meat/fish)',
    nameMl: 'സസ്യാഹാരം (വെജിറ്റേറിയൻ)',
    isActive: true,
  },
  {
    code: 'vegan',
    type: 'preference',
    nameEn: 'Vegan (100% plant-based)',
    nameMl: 'വീഗൻ (സമ്പൂർണ്ണ സസ്യഭക്ഷണം)',
    isActive: true,
  },
  {
    code: 'eggetarian',
    type: 'preference',
    nameEn: 'Eggetarian (Vegetarian with eggs)',
    nameMl: 'എഗ്ഗറ്റേറിയൻ (മുട്ട കഴിക്കുന്നവർ)',
    isActive: true,
  },
];

export const MASTER_ALLERGENS: DietaryRestriction[] = [
  {
    code: 'milk',
    type: 'allergen',
    nameEn: 'Milk / Dairy',
    nameMl: 'പാൽ / പാലുൽപ്പന്നങ്ങൾ',
    isActive: true,
  },
  {
    code: 'lactose',
    type: 'allergen',
    nameEn: 'Lactose',
    nameMl: 'ലാക്ടോസ്',
    isActive: true,
  },
  {
    code: 'peanut',
    type: 'allergen',
    nameEn: 'Peanut',
    nameMl: 'നിലക്കടല',
    isActive: true,
  },
  {
    code: 'tree_nuts',
    type: 'allergen',
    nameEn: 'Tree Nuts (Almonds, Cashews, Walnuts, etc.)',
    nameMl: 'കശുവണ്ടി, ബദാം തുടങ്ങിയ നട്ടുകൾ',
    isActive: true,
  },
  {
    code: 'soy',
    type: 'allergen',
    nameEn: 'Soy / Soya',
    nameMl: 'സോയ',
    isActive: true,
  },
  {
    code: 'wheat_gluten',
    type: 'allergen',
    nameEn: 'Wheat / Gluten',
    nameMl: 'ഗോതമ്പ് / ഗ്ലൂട്ടൻ',
    isActive: true,
  },
  {
    code: 'egg',
    type: 'allergen',
    nameEn: 'Egg',
    nameMl: 'മുട്ട',
    isActive: true,
  },
  {
    code: 'fish',
    type: 'allergen',
    nameEn: 'Fish',
    nameMl: 'മത്സ്യം',
    isActive: true,
  },
  {
    code: 'shellfish',
    type: 'allergen',
    nameEn: 'Shellfish / Prawns / Crab',
    nameMl: 'ചെമ്മീൻ / ഞണ്ട്',
    isActive: true,
  },
  {
    code: 'sesame',
    type: 'allergen',
    nameEn: 'Sesame',
    nameMl: 'എള്ള്',
    isActive: true,
  },
];

export const DEFAULT_HEURISTIC_RULES: HealthRule[] = [
  // Diabetes & Blood Sugar Guidance Rules (Per 100g)
  {
    id: 'rule-diabetes-added-sugar-high',
    conditionCode: 'diabetes',
    nutrient: 'addedSugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 10,
    unit: 'g',
    classification: 'INDIRECTLY_SUPPORTED',
    source: 'Draft FSSAI FoPL Solid Food Benchmark (2022)',
    severity: 'high',
    deduction: 30,
    messageEn: 'Exceeds Draft FSSAI FoPL benchmark for solid foods (≥10g added sugar per 100g).',
    messageMl: 'ഡ്രാഫ്റ്റ് FSSAI FoPL ബെഞ്ച്മാർക്കിനേക്കാൾ കൂടുതൽ ചേർത്ത പഞ്ചസാര (100 ഗ്രാമിൽ ≥10g).',
    adviceEn: 'When comparing similar products, consider options with less added sugar.',
    adviceMl: 'സമാന ഉൽപ്പന്നങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ പഞ്ചസാരയുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-diabetes-added-sugar-mod',
    conditionCode: 'diabetes',
    nutrient: 'addedSugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 5,
    unit: 'g',
    classification: 'HEURISTIC',
    source: 'FSSAI (2020) Low Sugar Claim Benchmark',
    severity: 'moderate',
    deduction: 15,
    messageEn: 'Exceeds FSSAI Low Sugar food-labelling claim benchmark (≥5g added sugar per 100g).',
    messageMl: 'FSSAI കുറഞ്ഞ പഞ്ചസാര എന്ന ലേബലിംഗ് മാനദണ്ഡത്തേക്കാൾ കൂടുതൽ പഞ്ചസാര (100 ഗ്രാമിൽ ≥5g).',
    adviceEn: 'When comparing similar products, consider options with less added sugar.',
    adviceMl: 'സമാന ഉൽപ്പന്നങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ പഞ്ചസാരയുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-diabetes-sugars-high',
    conditionCode: 'diabetes',
    nutrient: 'sugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 15,
    unit: 'g',
    classification: 'INDIRECTLY_SUPPORTED',
    source: 'Draft FSSAI FoPL Solid Food Benchmark (2022)',
    severity: 'high',
    deduction: 25,
    messageEn: 'Exceeds Draft FSSAI FoPL benchmark for total sugar (≥15g per 100g).',
    messageMl: 'ഡ്രാഫ്റ്റ് FSSAI FoPL ബെഞ്ച്മാർക്കിനേക്കാൾ കൂടുതൽ ആകെ പഞ്ചസാര (100 ഗ്രാമിൽ ≥15g).',
    adviceEn: 'When comparing similar products, consider options with less total sugar.',
    adviceMl: 'സമാന ഉൽപ്പന്നങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ പഞ്ചസാരയുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-prediabetes-sugar-high',
    conditionCode: 'prediabetes',
    nutrient: 'addedSugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 8,
    unit: 'g',
    classification: 'HEURISTIC',
    source: 'App-generated guidance heuristic',
    severity: 'high',
    deduction: 25,
    messageEn: 'Contains ≥8g added sugar per 100g (App-generated guidance heuristic for prediabetes).',
    messageMl: '100 ഗ്രാമിൽ ≥8g ചേർത്ത പഞ്ചസാര അടങ്ങിയിരിക്കുന്നു (ആപ്പ് നിർദ്ദേശിക്കുന്ന ഹ്യൂറിസ്റ്റിക്).',
    adviceEn: 'When comparing similar products, consider options with less added sugar.',
    adviceMl: 'സമാന ഉൽപ്പന്നങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ പഞ്ചസാരയുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },

  // Hypertension / High Blood Pressure Rules (Per 100g)
  {
    id: 'rule-hypertension-sodium-critical',
    conditionCode: 'hypertension',
    nutrient: 'sodiumMg',
    basis: 'per_100g',
    operator: '>=',
    threshold: 800,
    unit: 'mg',
    classification: 'INDIRECTLY_SUPPORTED',
    source: 'WHO Global Sodium Category Benchmarks (2021)',
    severity: 'critical',
    deduction: 35,
    messageEn: 'Exceeds WHO Global Sodium Category Benchmark for savoury snacks/noodles (≥800mg per 100g).',
    messageMl: 'WHO ഗ്ലോബൽ സോഡിയം ബെഞ്ച്മാർക്കിനേക്കാൾ കൂടുതൽ ഉപ്പ് (100 ഗ്രാമിൽ ≥800mg).',
    adviceEn: 'When comparing similar products, consider options with lower sodium.',
    adviceMl: 'സമാന ഉൽപ്പന്നങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ സോഡിയമുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-hypertension-sodium-high',
    conditionCode: 'hypertension',
    nutrient: 'sodiumMg',
    basis: 'per_100g',
    operator: '>=',
    threshold: 600,
    unit: 'mg',
    classification: 'INDIRECTLY_SUPPORTED',
    source: 'Draft FSSAI FoPL High Sodium Benchmark (2022)',
    severity: 'high',
    deduction: 20,
    messageEn: 'Exceeds Draft FSSAI FoPL benchmark for high sodium (≥600mg per 100g).',
    messageMl: 'ഡ്രാഫ്റ്റ് FSSAI FoPL ബെഞ്ച്മാർക്കിനേക്കാൾ കൂടുതൽ സോഡിയം (100 ഗ്രാമിൽ ≥600mg).',
    adviceEn: 'When comparing similar products, consider options with reduced sodium.',
    adviceMl: 'സമാന ഉൽപ്പന്നങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ ഉപ്പുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-hypertension-sodium-mod',
    conditionCode: 'hypertension',
    nutrient: 'sodiumMg',
    basis: 'per_100g',
    operator: '>=',
    threshold: 350,
    unit: 'mg',
    classification: 'HEURISTIC',
    source: 'App-generated guidance heuristic',
    severity: 'moderate',
    deduction: 10,
    messageEn: 'Contains ≥350mg sodium per 100g (App-generated guidance heuristic).',
    messageMl: '100 ഗ്രാമിൽ ≥350mg സോഡിയം അടങ്ങിയിരിക്കുന്നു (ആപ്പ് നിർദ്ദേശിക്കുന്ന ഹ്യൂറിസ്റ്റിക്).',
    isActive: true,
  },

  // High Cholesterol & Heart Health Rules
  {
    id: 'rule-cholesterol-satfat-high',
    conditionCode: 'high_cholesterol',
    nutrient: 'saturatedFatG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 5,
    unit: 'g',
    classification: 'INDIRECTLY_SUPPORTED',
    source: 'Draft FSSAI FoPL Solid Food Benchmark (2022)',
    severity: 'high',
    deduction: 25,
    messageEn: 'Exceeds Draft FSSAI FoPL benchmark for saturated fat (≥5g per 100g).',
    messageMl: 'ഡ്രാഫ്റ്റ് FSSAI FoPL ബെഞ്ച്മാർക്കിനേക്കാൾ കൂടുതൽ സാച്ചുറേറ്റഡ് ഫാറ്റ് (100 ഗ്രാമിൽ ≥5g).',
    adviceEn: 'When comparing similar products, consider options with less saturated fat.',
    adviceMl: 'സമാന ഉൽപ്പന്നങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ പൂരിത കൊഴുപ്പുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-cholesterol-transfat',
    conditionCode: 'high_cholesterol',
    nutrient: 'transFatG',
    basis: 'per_100g',
    operator: '>',
    threshold: 0.2,
    unit: 'g',
    classification: 'INDIRECTLY_SUPPORTED',
    source: 'FSSAI (2022) Trans Fat Free Claim Limit (≤0.2g/100g)',
    severity: 'critical',
    deduction: 30,
    messageEn: 'Exceeds FSSAI Trans-Fat-Free food-labelling claim limit (>0.2g trans fat per 100g).',
    messageMl: 'FSSAI ട്രാൻസ് ഫാറ്റ് ഫ്രീ ലേബലിംഗ് നിബന്ധനയേക്കാൾ കൂടുതൽ (>0.2g ട്രാൻസ് ഫാറ്റ് / 100g).',
    adviceEn: 'When comparing similar products, consider options with zero trans fat.',
    adviceMl: 'ട്രാൻസ് ഫാറ്റ് പൂർണ്ണമായും ഇല്ലാത്തവ തിരഞ്ഞെടുക്കാൻ ശ്രദ്ധിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-heart-satfat',
    conditionCode: 'heart_health',
    nutrient: 'saturatedFatG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 4,
    unit: 'g',
    classification: 'HEURISTIC',
    source: 'App-generated guidance heuristic',
    severity: 'high',
    deduction: 20,
    messageEn: 'Contains ≥4g saturated fat per 100g (App-generated guidance heuristic).',
    messageMl: '100 ഗ്രാമിൽ ≥4g സാച്ചുറേറ്റഡ് ഫാറ്റ് അടങ്ങിയിരിക്കുന്നു (ആപ്പ് നിർദ്ദേശിക്കുന്ന ഹ്യൂറിസ്റ്റിക്).',
    isActive: true,
  },

  // Weight Management
  {
    id: 'rule-weight-energy-high',
    conditionCode: 'weight_management',
    nutrient: 'energyKcal',
    basis: 'per_100g',
    operator: '>=',
    threshold: 450,
    unit: 'kcal',
    classification: 'HEURISTIC',
    source: 'App-generated guidance heuristic',
    severity: 'moderate',
    deduction: 15,
    messageEn: 'High energy density (≥450 kcal per 100g; App-generated guidance heuristic).',
    messageMl: 'കൂടിയ കലോറി സാന്ദ്രത (100 ഗ്രാമിൽ ≥450 കിലോ കലോറി; ആപ്പ് ഹ്യൂറിസ്റ്റിക്).',
    adviceEn: 'When comparing similar snacks, consider lower energy density options.',
    adviceMl: 'കുറഞ്ഞ കലോറിയുള്ളവ തിരഞ്ഞെടുക്കാൻ ശ്രദ്ധിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-weight-sugar-high',
    conditionCode: 'weight_management',
    nutrient: 'sugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 6,
    unit: 'g',
    classification: 'INDIRECTLY_SUPPORTED',
    source: 'Draft FSSAI FoPL Liquid Benchmark (2022)',
    severity: 'moderate',
    deduction: 15,
    messageEn: 'Exceeds Draft FSSAI FoPL benchmark for liquid foods/beverages (≥6g sugar per 100ml).',
    messageMl: 'ഡ്രാഫ്റ്റ് FSSAI FoPL പാനീയ ബെഞ്ച്മാർക്കിനേക്കാൾ കൂടുതൽ പഞ്ചസാര (100 മില്ലിയിൽ ≥6g).',
    adviceEn: 'When comparing similar products, consider options with less sugar.',
    adviceMl: 'സമാന ഉൽപ്പന്നങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ പഞ്ചസാരയുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-diabetes-liquid-sugar-high',
    conditionCode: 'diabetes',
    nutrient: 'sugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 6,
    unit: 'g',
    classification: 'INDIRECTLY_SUPPORTED',
    source: 'Draft FSSAI FoPL Liquid Benchmark (2022)',
    severity: 'high',
    deduction: 25,
    messageEn: 'Exceeds Draft FSSAI FoPL benchmark for liquid foods/beverages (≥6g sugar per 100ml).',
    messageMl: 'ഡ്രാഫ്റ്റ് FSSAI FoPL പാനീയ ബെഞ്ച്മാർക്കിനേക്കാൾ കൂടുതൽ പഞ്ചസാര (100 മില്ലിയിൽ ≥6g).',
    adviceEn: 'When comparing similar beverages, consider options with lower sugar.',
    adviceMl: 'സമാന പാനീയങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ പഞ്ചസാരയുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },
  {
    id: 'rule-prediabetes-liquid-sugar-high',
    conditionCode: 'prediabetes',
    nutrient: 'sugarsG',
    basis: 'per_100g',
    operator: '>=',
    threshold: 6,
    unit: 'g',
    classification: 'INDIRECTLY_SUPPORTED',
    source: 'Draft FSSAI FoPL Liquid Benchmark (2022)',
    severity: 'high',
    deduction: 20,
    messageEn: 'Exceeds Draft FSSAI FoPL benchmark for liquid foods/beverages (≥6g sugar per 100ml).',
    messageMl: 'ഡ്രാഫ്റ്റ് FSSAI FoPL പാനീയ ബെഞ്ച്മാർക്കിനേക്കാൾ കൂടുതൽ പഞ്ചസാര (100 മില്ലിയിൽ ≥6g).',
    adviceEn: 'When comparing similar beverages, consider options with lower sugar.',
    adviceMl: 'സമാന പാനീയങ്ങളുമായി താരതമ്യം ചെയ്യുമ്പോൾ കുറഞ്ഞ പഞ്ചസാരയുള്ളവ പരിഗണിക്കുക.',
    isActive: true,
  },
];

export const MANDATORY_MEDICAL_DISCLAIMER_EN =
  'This app provides general nutritional information and a Personalized Guidance Score based on public guidelines (FSSAI, ICMR-NIN, WHO) and your selected preferences. It is an app-generated heuristic, not medical advice, a clinical diagnosis, or a guarantee of safety. Always consult a qualified healthcare professional for medical decisions.';

export const MANDATORY_MEDICAL_DISCLAIMER_ML =
  'ഈ ആപ്പ് നൽകുന്നത് പൊതുവായ പോഷകാഹാര വിവരങ്ങളും നിങ്ങളുടെ തിരഞ്ഞെടുപ്പുകൾക്ക് അനുസൃതമായ പേഴ്സണലൈസ്ഡ് ഗൈഡൻസ് സ്കോറും മാത്രമാണ്. ഇത് ആപ്പ് നൽകുന്ന ഒരു സൂചന മാത്രമാണ്, വൈദ്യോപദേശമോ ക്ലിനിക്കൽ രോഗനിർണ്ണയമോ അല്ല. ആരോഗ്യപരമായ തീരുമാനങ്ങൾക്ക് എപ്പോഴും ഡോക്ടറുടെ സേവനം തേടുക.';
